### PR TITLE
ENH: speedup of abeles function

### PR DESCRIPTION
**Pull request by andyfaff**
I'm also interested in learning a bit more about Julia, and I just found your code. I rewrote the refnx refcalc.cpp in [different ways](https://gist.github.com/andyfaff/cc26b87da9eaf47833c3d99c4f6b7e68), and came up with this PR.
I got the following outputs from benchmarking the existing code, and my proposed modifications. The two are surprisingly similar. There is no threading in here, I didn't find it gave a speedup. Hopefully the code should still work with `ForwardDiff`.

```
>>> using BenchmarkTools
>>> w = [[0 2.07 0 0]
     [100 3.47 0 3]
     [500 -0.5 0.00001 3]
     [0 6.36 0 3]]

>>> q = Array(LinRange(0.01, 0.5, 1000))
>>> # existing Jeff code
>>> @benchmark abeles(q, w)
BenchmarkTools.Trial: 
  memory estimate:  2.22 MiB
  allocs estimate:  68016
  --------------
  minimum time:     1.571 ms (0.00% GC)
  median time:      1.742 ms (0.00% GC)
  mean time:        1.996 ms (11.30% GC)
  maximum time:     47.865 ms (95.98% GC)
  --------------
  samples:          2502
  evals/sample:     1

>>> # using this PR
>>> @benchmark abeles3(q, w)
BenchmarkTools.Trial: 
  memory estimate:  55.98 KiB
  allocs estimate:  10
  --------------
  minimum time:     323.171 μs (0.00% GC)
  median time:      352.502 μs (0.00% GC)
  mean time:        376.364 μs (2.54% GC)
  maximum time:     51.587 ms (99.27% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

### CODE REVIEW

**Comment by andyfaff** [comment]
I did a quick check of pointwise smearing against refnx and the two match up. I didn't add a test here though.
To calculate the Gauss Legendre weights another package, `FastGaussQuadrature` is needed. I'm not sure how to add the package to Project.toml, that's why the tests are failing.

**Comment by andyfaff** [comment]
I added `FastGaussQuadrature` to `Project.toml` by:

- `activate .`
- `update`
- `add FastGaussQuadrature`

in `pkg` mode in the Julia REPL. This seems to have updated a lot of stuff in the manifest. Please let me know if you'd like me to back that out.

**Comment by andyfaff** [comment]
Whilst this abeles seems to be a lot faster I don't think it's going to work with ForwardDiff immediately, because I'm using `Vector{ComplexF64}(sz)` instead of `Vector{Any}(sz)`. Apparently some of these issues are fixed in nightly builds of Julia/most recent ForwardDiff.
I'll see if I can get things to work with that.

**Comment by arm61** [comment]
Yeah if I remember correctly, I was using 1.6.1 or similar to get the `ForwardDiff` to work.

**Comment by andyfaff** [comment]
Ok, it turns out that it's a bad idea to have any `Vector{Any}`. Whilst they're needed for `ForwardDiff` they slow down the reflectivity calculation as there are lots of allocations.

aec7901 removes all `Vector{Any}` instances replacing with straight variables. Local testing shows the reflectivity calculation is still fast, and that ForwardDiff doesn't complain. Not complaining doesn't mean that I've tested the gradient against a finite difference differentiation, just that calculating an autodiffed gradient works.

**Comment by arm61** [comment]
What is the `@benchmark` without the `Vector{Any}`?

**Comment by andyfaff** [comment]
```
>>> w = [[0 2.07 0 0]
     [100 3.47 0 3]
     [500 -0.5 0.00001 3]
     [0 6.36 0 3]]

>>> q = Array(LinRange(0.01, 0.5, 1000))
>>>@benchmark abeles(q, w)

BenchmarkTools.Trial: 
  memory estimate:  187.94 KiB
  allocs estimate:  4993
  --------------
  minimum time:     435.128 μs (0.00% GC)
  median time:      439.698 μs (0.00% GC)
  mean time:        461.373 μs (3.52% GC)
  maximum time:     39.935 ms (98.87% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

Not as good as I first had, but should differentiate ok. Before  it's merged you should look over the toml files. I don't think I quite have the full hang of that aspect yet.

**Comment by andyfaff** [comment]
Not sure how to resolve merge conflicts in Manifest.toml.

**Comment by andyfaff** [comment]
Added ORSO tests for abeles kernel, including absorption effects. 

Test `pointwise_smearing` calculation. The tolerances on this are quite loose at the moment (rtol=0.03), it may warrant more investigation of the pointwise smearing calculation.

**Comment by andyfaff** [comment]
Add perform a better `constant_smearing` check

**Comment by arm61** [comment]
Very nice PR. And a great speed up too!

**Pull request merged**
